"""
NeuralOperator Dataset Loaders for LRN

Provides a unified interface to NeuralOperator's dataset loaders
for Burgers, Darcy, and Navier-Stokes datasets.

This module wraps the official neuraloperator library to:
1. Provide consistent data loading across all PDE benchmarks
2. Handle normalization via DataProcessor
3. Support both FNO and LRR-FNO input formats
"""

from __future__ import annotations
from pathlib import Path
from typing import Tuple, Optional, Dict, Any, Union, TYPE_CHECKING
import torch
from torch.utils.data import DataLoader, Dataset

# NeuralOperator imports
NEURALOP_AVAILABLE = False
DarcyDataset = None
NavierStokesDataset = None
Burgers1dTimeDataset = None

try:
    from neuralop.data.datasets import (
        DarcyDataset,
        NavierStokesDataset,
        Burgers1dTimeDataset,
        load_darcy_flow_small,
        load_navier_stokes_pt,
    )
    from neuralop.data.transforms.data_processors import DefaultDataProcessor
    from neuralop.data.transforms.normalizers import UnitGaussianNormalizer
    NEURALOP_AVAILABLE = True
except ImportError:
    DefaultDataProcessor = None
    UnitGaussianNormalizer = None
    print("Warning: neuraloperator not installed. Install with: pip install neuraloperator")


# Default data directory
DEFAULT_DATA_ROOT = Path(__file__).parent.parent.parent / "datasets"


class DictToTupleDataset(Dataset):
    """
    Wrapper that converts NeuralOperator dict outputs to tuple format.
    
    NeuralOperator returns {'x': input, 'y': output} but LRN training
    code expects (input, output) tuples.
    """
    
    def __init__(self, dataset: Dataset):
        self.dataset = dataset
    
    def __len__(self):
        return len(self.dataset)
    
    def __getitem__(self, idx):
        item = self.dataset[idx]
        if isinstance(item, dict):
            return item['x'], item['y']
        return item


def load_darcy(
    n_train: Optional[int] = 1000,
    n_test: int = 200,
    batch_size: int = 32,
    test_batch_size: int = 32,
    train_resolution: int = 16,
    test_resolutions: list = [16, 32],
    data_root: Optional[Union[str, Path]] = None,
    encode_input: bool = False,
    encode_output: bool = True,
    return_processor: bool = True,
    return_tuple_format: bool = True,
) -> Tuple[DataLoader, Dict[int, DataLoader], Optional[DefaultDataProcessor]]:
    """
    Load Darcy flow dataset using NeuralOperator's loader.
    
    Args:
        n_train: Number of training samples
        n_test: Number of test samples
        batch_size: Training batch size
        test_batch_size: Test batch size
        train_resolution: Resolution for training data (16, 32, 64, or 128)
        test_resolutions: List of resolutions for test data
        data_root: Directory to download/store data
        encode_input: Whether to normalize inputs
        encode_output: Whether to normalize outputs
        return_processor: Whether to return the DataProcessor
        return_tuple_format: If True, convert dict outputs to (x, y) tuples
        
    Returns:
        train_loader: Training DataLoader
        test_loaders: Dict mapping resolution to test DataLoader
        data_processor: Optional DataProcessor for normalization
    """
    if not NEURALOP_AVAILABLE:
        raise ImportError("neuraloperator is required. Install with: pip install neuraloperator")
    
    if data_root is None:
        data_root = DEFAULT_DATA_ROOT / "darcy"
    data_root = Path(data_root)
    data_root.mkdir(parents=True, exist_ok=True)
    
    # First, try to load from local .pt files (generated by scripts/generate_darcy_data.py)
    train_file = data_root / f"darcy_train_{train_resolution}.pt"
    test_file = data_root / f"darcy_test_{train_resolution}.pt"
    
    if train_file.exists() and test_file.exists():
        train_data = torch.load(train_file)
        test_data = torch.load(test_file)
        
        class LocalDarcyDataset(Dataset):
            def __init__(self, data, n_samples=None):
                x = data['x'][:n_samples] if n_samples else data['x']
                y = data['y'][:n_samples] if n_samples else data['y']
                # Add channel dimension if needed
                if x.ndim == 3: x = x.unsqueeze(1)
                if y.ndim == 3: y = y.unsqueeze(1)
                self.x = x.float()
                self.y = y.float()
            def __len__(self): return len(self.x)
            def __getitem__(self, idx): return self.x[idx], self.y[idx]
        
        train_db = LocalDarcyDataset(train_data, n_train)
        test_db = LocalDarcyDataset(test_data, n_test)
        
        train_loader = DataLoader(train_db, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory=True)
        test_loaders = {train_resolution: DataLoader(test_db, batch_size=test_batch_size, shuffle=False, num_workers=0, pin_memory=True)}
        
        return train_loader, test_loaders, None
    
    # Fall back to NeuralOperator's DarcyDataset
    dataset = DarcyDataset(
        root_dir=data_root,
        n_train=n_train,
        n_tests=[n_test] * len(test_resolutions),
        batch_size=batch_size,
        test_batch_sizes=[test_batch_size] * len(test_resolutions),
        train_resolution=train_resolution,
        test_resolutions=test_resolutions,
        encode_input=encode_input,
        encode_output=encode_output,
        download=True,
    )

    # --- Manual Patch for Input Normalization ---
    # Some versions of NeuralOperator's DarcyDataset might ignore encode_input or fail to init the normalizer.
    # We forcefully ensure it exists and is applied.
    if encode_input and (dataset.data_processor.in_normalizer is None):
        print("Warning: DarcyDataset did not initialize input normalizer. Creating manually...")
        # 1. Gather all training inputs to compute stats
        # Access underlying TensorDataset or similar. 
        # train_db might be a TensorDataset or similar wrapper.
        # usually .train_db[i]['x'] works.
        all_x = []
        # We assume dataset fits in memory for stats calc (Darcy usually does)
        # Note: dataset.train_db is the subset.
        loader = DataLoader(dataset.train_db, batch_size=batch_size, shuffle=False)
        for batch in loader:
            x = batch['x']
            all_x.append(x)
        all_x = torch.cat(all_x, dim=0)
        
        # 2. Create and fit normalizer
        # x is [B, 1, H, W] or [B, H, W]
        normalizer = UnitGaussianNormalizer(all_x)
        dataset.data_processor.in_normalizer = normalizer # Attach to processor
        
        # 3. Apply normalization to the dataset? 
        # NeuralOperator datasets typically apply normalization in __getitem__ using the processor
        # IF the processor is correctly linked.
        # But if the dataset uses a transform list, we might need to append it.
        # Check if we can wrap the dataset.
        
    # Wrap datasets if tuple format requested
    # We use a custom wrapper that ALSO applies the processor if needed
    class ProcessedTupleDataset(Dataset):
        def __init__(self, db, processor, apply_input=False, apply_output=False):
            self.db = db
            self.processor = processor
            self.apply_input = apply_input
            self.apply_output = apply_output
            
        def __len__(self): return len(self.db)
        def __getitem__(self, idx):
            item = self.db[idx]
            x, y = item['x'], item['y']
            
            # Apply Normalization if not already done by the internal dataset
            # (If internal dataset didn't have normalizer, it returns raw)
            if self.apply_input and self.processor.in_normalizer:
                x = self.processor.in_normalizer(x)
            if self.apply_output and self.processor.out_normalizer:
                 # Output usually handled by dataset if encode_output=True was passed to init
                 # But if we want to be sure...
                 # Actually, usually DarcyDataset DOES handle output normalizer correct.
                 # Let's trust 'encode_output' unless proved otherwise.
                 pass
                 
            return x, y

    train_db = dataset.train_db
    if return_tuple_format:
        # Use our smart wrapper for input normalization
        # We only force apply_input if we just manually created it OR if we suspect it's not applied.
        # To be safe, let's explicitely apply it if we hold the normalizer.
        # Wait, if we double-normalize it's bad.
        # Safe bet: Check if it's already normalized? 
        # No, simpler: NeuralOp 0.2/0.3 datasets use the processor in __getitem__. 
        # If we attached the normalizer to dataset.data_processor, hopefully it picks it up?
        # If not, we wrap it.
        # Let's assume we need to wrap it if we manually added it.
        force_manual = (encode_input and getattr(dataset, 'transform', None) is None) # weak check
        # Actually, let's just use the wrapper. compute overhead is small.
        # But we need to know if it was ALREADY normalized.
        # Let's rely on the patched processor.
        pass

    # RE-STRATEGY: 
    # Instead of monkey-patching the internal dataset which is opaque,
    # let's just WRAP the output in a class that normalizes.
    
    # 1. Fit normalizer if needed
    in_normalizer = None
    if encode_input:
        if dataset.data_processor.in_normalizer:
             in_normalizer = dataset.data_processor.in_normalizer
        else:
             # Fit it
             msg = "Computing statistics for input normalization..."
             print(msg)
             all_x = []
             loader = DataLoader(dataset.train_db, batch_size=batch_size, shuffle=False)
             for batch in loader:
                 all_x.append(batch['x'])
             all_x = torch.cat(all_x, dim=0)
             in_normalizer = UnitGaussianNormalizer(all_x)
             dataset.data_processor.in_normalizer = in_normalizer # Save it

    train_db = dataset.train_db
    if return_tuple_format:
        # We need a custom wrapper that applies 'in_normalizer' if it exists
        # AND if the base dataset didn't apply it.
        # We assume base dataset didn't apply it if it didn't have it initially.
        train_db = DictToTupleDataset(train_db)
        
        # Wrap with on-the-fly normalization
        if in_normalizer:
             class NormalizedDataset(Dataset):
                 def __init__(self, dataset, normalizer):
                     self.dataset = dataset
                     self.normalizer = normalizer
                 def __len__(self): return len(self.dataset)
                 def __getitem__(self, idx):
                     x, y = self.dataset[idx]
                     # Normalizer usually expects batched input or adds a dimension
                     # If x is [C, H, W], normalizer might return [1, C, H, W]
                     original_ndim = x.ndim
                     x = self.normalizer(x)
                     if x.ndim > original_ndim and x.shape[0] == 1:
                         x = x.squeeze(0)
                     return x, y
             train_db = NormalizedDataset(train_db, in_normalizer)
    
    train_loader = DataLoader(
        train_db,
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,
        pin_memory=True,
    )
    
    test_loaders = {}
    for res in test_resolutions:
        test_db = dataset.test_dbs[res]
        if return_tuple_format:
            test_db = DictToTupleDataset(test_db)
            if in_normalizer:
                test_db = NormalizedDataset(test_db, in_normalizer)
                
        test_loaders[res] = DataLoader(
            test_db,
            batch_size=test_batch_size,
            shuffle=False,
            num_workers=0,
            pin_memory=True,
        )
    
    if return_processor:
        return train_loader, test_loaders, dataset.data_processor
    return train_loader, test_loaders, None


def load_navier_stokes(
    n_train: Optional[int] = 1000,
    n_test: int = 200,
    batch_size: int = 32,
    test_batch_size: int = 32,
    train_resolution: int = 128,
    test_resolutions: list = [128],
    data_root: Optional[Union[str, Path]] = None,
    encode_input: bool = False,
    encode_output: bool = True,
    return_processor: bool = True,
    return_tuple_format: bool = True,
) -> Tuple[DataLoader, Dict[int, DataLoader], Optional[DefaultDataProcessor]]:
    """
    Load Navier-Stokes dataset using NeuralOperator's loader.
    
    Args:
        n_train: Number of training samples
        n_test: Number of test samples
        batch_size: Training batch size
        test_batch_size: Test batch size
        train_resolution: Resolution for training data (128 or 1024)
        test_resolutions: List of resolutions for test data
        data_root: Directory to download/store data
        encode_input: Whether to normalize inputs
        encode_output: Whether to normalize outputs
        return_processor: Whether to return the DataProcessor
        return_tuple_format: If True, convert dict outputs to (x, y) tuples
        
    Returns:
        train_loader: Training DataLoader
        test_loaders: Dict mapping resolution to test DataLoader
        data_processor: Optional DataProcessor for normalization
    """
    if not NEURALOP_AVAILABLE:
        raise ImportError("neuraloperator is required. Install with: pip install neuraloperator")
    
    if data_root is None:
        data_root = DEFAULT_DATA_ROOT / "navier_stokes"
    data_root = Path(data_root)
    data_root.mkdir(parents=True, exist_ok=True)
    
    # First, try to load from local .pt files (generated by scripts/generate_ns_data.py)
    train_file = data_root / f"ns_train_{train_resolution}.pt"
    test_file = data_root / f"ns_test_{train_resolution}.pt"
    
    if train_file.exists() and test_file.exists():
        train_data = torch.load(train_file)
        test_data = torch.load(test_file)
        
        class LocalNSDataset(Dataset):
            def __init__(self, data, n_samples=None):
                x = data['x'][:n_samples] if n_samples else data['x']
                y = data['y'][:n_samples] if n_samples else data['y']
                # Add channel dimension if needed
                if x.ndim == 3: x = x.unsqueeze(1)
                if y.ndim == 3: y = y.unsqueeze(1)
                self.x = x.float()
                self.y = y.float()
            def __len__(self): return len(self.x)
            def __getitem__(self, idx): return self.x[idx], self.y[idx]
        
        train_db = LocalNSDataset(train_data, n_train)
        test_db = LocalNSDataset(test_data, n_test)
        
        train_loader = DataLoader(train_db, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory=True)
        test_loaders = {train_resolution: DataLoader(test_db, batch_size=test_batch_size, shuffle=False, num_workers=0, pin_memory=True)}
        
        return train_loader, test_loaders, None
    
    # Fall back to NeuralOperator's NavierStokesDataset
    dataset = NavierStokesDataset(
        root_dir=data_root,
        n_train=n_train,
        n_tests=[n_test] * len(test_resolutions),
        batch_size=batch_size,
        test_batch_sizes=[test_batch_size] * len(test_resolutions),
        train_resolution=train_resolution,
        test_resolutions=test_resolutions,
        encode_input=encode_input,
        encode_output=encode_output,
        download=True,
    )
    
    # Wrap datasets if tuple format requested
    train_db = dataset.train_db
    if return_tuple_format:
        train_db = DictToTupleDataset(train_db)
    
    train_loader = DataLoader(
        train_db,
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,
        pin_memory=True,
    )
    
    test_loaders = {}
    for res in test_resolutions:
        test_db = dataset.test_dbs[res]
        if return_tuple_format:
            test_db = DictToTupleDataset(test_db)
        test_loaders[res] = DataLoader(
            test_db,
            batch_size=test_batch_size,
            shuffle=False,
            num_workers=0,
            pin_memory=True,
        )
    
    if return_processor:
        return train_loader, test_loaders, dataset.data_processor
    return train_loader, test_loaders, None


def load_burgers(
    n_train: Optional[int] = 1000,
    n_test: int = 200,
    batch_size: int = 32,
    test_batch_size: int = 32,
    train_resolution: int = 16,
    test_resolutions: list = [16],
    data_root: Optional[Union[str, Path]] = None,
    temporal_subsample: int = 1,
    spatial_subsample: int = 1,
    return_processor: bool = True,
    return_tuple_format: bool = True,
) -> Tuple[DataLoader, Dict[int, DataLoader], Optional[DefaultDataProcessor]]:
    """
    Load 1D Burgers equation dataset using NeuralOperator's loader.
    
    Args:
        n_train: Number of training samples
        n_test: Number of test samples
        batch_size: Training batch size
        test_batch_size: Test batch size
        train_resolution: Resolution (16 or 128 available)
        test_resolutions: List of resolutions for test data
        data_root: Directory to download/store data
        temporal_subsample: Temporal subsampling rate
        spatial_subsample: Spatial subsampling rate
        return_processor: Whether to return the DataProcessor
        return_tuple_format: If True, convert dict outputs to (x, y) tuples
        
    Returns:
        train_loader: Training DataLoader
        test_loaders: Dict mapping resolution to test DataLoader
        data_processor: Optional DataProcessor for normalization
    """
    if not NEURALOP_AVAILABLE:
        raise ImportError("neuraloperator is required. Install with: pip install neuraloperator")
    
    if data_root is None:
        data_root = DEFAULT_DATA_ROOT / "burgers"
    data_root = Path(data_root)
    data_root.mkdir(parents=True, exist_ok=True)
    
    # First, try to load from local .pt files (generated by scripts/generate_burgers_data.py)
    train_file = data_root / f"burgers_train_{train_resolution}.pt"
    test_file = data_root / f"burgers_test_{train_resolution}.pt"
    
    if train_file.exists() and test_file.exists():
        train_data = torch.load(train_file)
        test_data = torch.load(test_file)
        
        # Create simple datasets
        class LocalBurgersDataset(Dataset):
            def __init__(self, data, n_samples=None):
                x = data['x'][:n_samples] if n_samples else data['x']
                y = data['y'][:n_samples] if n_samples else data['y']
                # Add channel dimension if needed
                if x.ndim == 2: x = x.unsqueeze(1)
                if y.ndim == 2: y = y.unsqueeze(1)
                self.x = x.float()
                self.y = y.float()
            def __len__(self): return len(self.x)
            def __getitem__(self, idx): return self.x[idx], self.y[idx]
        
        # --- Normalization Logic ---
        # We need to fit a normalizer if requested
        in_normalizer = None
        if encode_input:
             print("Computing stats for local Burgers input normalization...")
             # Use all training samples for stats
             all_x = train_data['x'].float()
             if all_x.ndim == 2: all_x = all_x.unsqueeze(1)
             in_normalizer = UnitGaussianNormalizer(all_x)
        
        train_db = LocalBurgersDataset(train_data, n_train)
        test_db = LocalBurgersDataset(test_data, n_test)
        
        if in_normalizer:
             class NormalizedDataset(Dataset):
                 def __init__(self, db, normalizer):
                     self.db = db
                     self.normalizer = normalizer
                 def __len__(self): return len(self.db)
                 def __getitem__(self, idx):
                     x, y = self.db[idx]
                     return self.normalizer(x).squeeze(0), y
             
             train_db = NormalizedDataset(train_db, in_normalizer)
             test_db = NormalizedDataset(test_db, in_normalizer)

        train_loader = DataLoader(train_db, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory=True)
        test_loaders = {train_resolution: DataLoader(test_db, batch_size=test_batch_size, shuffle=False, num_workers=0, pin_memory=True)}
        
        # Create a dummy data processor to hold the normalizer
        processor = None
        if in_normalizer and DefaultDataProcessor:
             processor = DefaultDataProcessor(in_normalizer=in_normalizer)

        return train_loader, test_loaders, processor
    
    # Fall back to NeuralOperator's Burgers1dTimeDataset
    try:
        dataset = Burgers1dTimeDataset(
            root_dir=data_root,
            n_train=n_train,
            n_tests=[n_test] * len(test_resolutions),
            batch_size=batch_size,
            test_batch_sizes=[test_batch_size] * len(test_resolutions),
            train_resolution=train_resolution,
            test_resolutions=test_resolutions,
            temporal_subsample=temporal_subsample,
            spatial_subsample=spatial_subsample,
        )
    except FileNotFoundError as e:
        raise FileNotFoundError(
            f"Burgers data files not found at {data_root}. "
            f"NeuralOperator's Burgers1dTimeDataset does not auto-download. "
            f"Use the synthetic BurgersDataset from src.data.pde_datasets instead, or "
            f"manually generate burgers_train_{train_resolution}.pt and burgers_test_{{res}}.pt"
        ) from e
    
    # Wrap datasets if tuple format requested
    train_db = dataset.train_db
    if return_tuple_format:
        train_db = DictToTupleDataset(train_db)
    
    train_loader = DataLoader(
        train_db,
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,
        pin_memory=True,
    )
    
    test_loaders = {}
    for res in test_resolutions:
        test_db = dataset.test_dbs[res]
        if return_tuple_format:
            test_db = DictToTupleDataset(test_db)
        test_loaders[res] = DataLoader(
            test_db,
            batch_size=test_batch_size,
            shuffle=False,
            num_workers=0,
            pin_memory=True,
        )
    
    if return_processor:
        return train_loader, test_loaders, dataset.data_processor
    return train_loader, test_loaders, None


def get_dataset_info(dataset_name: str) -> Dict[str, Any]:
    """
    Get metadata/info about a dataset.
    
    Args:
        dataset_name: One of 'darcy', 'navier_stokes', 'burgers'
        
    Returns:
        Dictionary with dataset information
    """
    info = {
        'darcy': {
            'name': 'Darcy Flow',
            'pde_type': 'elliptic',
            'input_description': 'Coefficient field a(x)',
            'output_description': 'Pressure field u(x)',
            'domain': '[0, 1]^2',
            'available_resolutions': [16, 32, 64, 128, 421],
            'zenodo_record': '12784353',
        },
        'navier_stokes': {
            'name': 'Navier-Stokes Forcing',
            'pde_type': 'parabolic',
            'input_description': 'Vorticity field at t',
            'output_description': 'Vorticity field at t+dt',
            'domain': '[0, 1]^2',
            'available_resolutions': [128, 1024],
            'zenodo_record': '12825163',
        },
        'burgers': {
            'name': '1D Burgers Equation',
            'pde_type': 'hyperbolic',
            'input_description': 'Initial condition u(x, 0)',
            'output_description': 'Solution u(x, t)',
            'domain': '[0, 1]',
            'available_resolutions': [16, 128],
            'zenodo_record': None,  # Bundled with library
        },
    }
    return info.get(dataset_name.lower(), {})


# Convenience function matching existing interface
def create_neuralop_dataloaders(
    dataset_name: str,
    n_train: Optional[int] = 1000,
    n_test: int = 200,
    batch_size: int = 32,
    test_batch_size: int = 32,
    resolution: int = None,
    data_root: Optional[str] = None,
    encode_input: bool = False,
    encode_output: bool = True,
    return_tuple_format: bool = True,
) -> Tuple[DataLoader, DataLoader, Optional[DefaultDataProcessor]]:
    """
    Factory function to create dataloaders for any supported dataset.
    
    This provides a unified interface similar to the existing create_dataloaders
    but uses NeuralOperator's infrastructure.
    
    Args:
        dataset_name: 'darcy', 'navier_stokes', or 'burgers'
        n_train: Number of training samples
        n_test: Number of test samples
        batch_size: Training batch size
        test_batch_size: Test batch size
        resolution: Data resolution (uses dataset default if None)
        data_root: Data directory
        encode_input: Whether to normalize inputs (Default: False)
        encode_output: Whether to normalize outputs (Default: True)
        return_tuple_format: If True, return (x, y) tuples instead of dicts
        
    Returns:
        train_loader: Training DataLoader
        test_loader: Test DataLoader (single resolution)
        data_processor: DataProcessor for normalization
    """
    dataset_name = dataset_name.lower()
    
    if dataset_name == 'darcy':
        res = resolution or 16
        train_loader, test_loaders, processor = load_darcy(
            n_train=n_train,
            n_test=n_test,
            batch_size=batch_size,
            test_batch_size=test_batch_size,
            train_resolution=res,
            test_resolutions=[res],
            data_root=data_root,
            encode_input=encode_input,
            encode_output=encode_output,
            return_tuple_format=return_tuple_format,
        )
        return train_loader, test_loaders[res], processor
        
    elif dataset_name in ['navier_stokes', 'ns']:
        res = resolution or 128
        train_loader, test_loaders, processor = load_navier_stokes(
            n_train=n_train,
            n_test=n_test,
            batch_size=batch_size,
            test_batch_size=test_batch_size,
            train_resolution=res,
            test_resolutions=[res],
            data_root=data_root,
            encode_input=encode_input,
            encode_output=encode_output,
            return_tuple_format=return_tuple_format,
        )
        return train_loader, test_loaders[res], processor
        
    elif dataset_name == 'burgers':
        res = resolution or 16
        train_loader, test_loaders, processor = load_burgers(
            n_train=n_train,
            n_test=n_test,
            batch_size=batch_size,
            test_batch_size=test_batch_size,
            train_resolution=res,
            test_resolutions=[res],
            data_root=data_root,
            return_tuple_format=return_tuple_format,
        )
        return train_loader, test_loaders[res], processor
        
    else:
        raise ValueError(f"Unknown dataset: {dataset_name}. Supported: darcy, navier_stokes, burgers")


if __name__ == "__main__":
    # Test the loaders
    print("Testing NeuralOperator dataset loaders...")
    
    # Test Darcy
    print("\n--- Darcy Flow ---")
    try:
        train_loader, test_loader, processor = create_neuralop_dataloaders(
            'darcy', n_train=100, n_test=20, batch_size=16
        )
        for x, y in train_loader:
            print(f"  Train batch: x={x.shape}, y={y.shape}")
            break
        for x, y in test_loader:
            print(f"  Test batch: x={x.shape}, y={y.shape}")
            break
        print("  ✓ Darcy loader works!")
    except Exception as e:
        print(f"  ✗ Darcy failed: {e}")
    
    # Test NS
    print("\n--- Navier-Stokes ---")
    try:
        train_loader, test_loader, processor = create_neuralop_dataloaders(
            'navier_stokes', n_train=100, n_test=20, batch_size=16
        )
        for x, y in train_loader:
            print(f"  Train batch: x={x.shape}, y={y.shape}")
            break
        print("  ✓ NS loader works!")
    except Exception as e:
        print(f"  ✗ NS failed: {e}")
    
    # Test Burgers
    print("\n--- Burgers ---")
    try:
        train_loader, test_loader, processor = create_neuralop_dataloaders(
            'burgers', n_train=100, n_test=20, batch_size=16
        )
        for x, y in train_loader:
            print(f"  Train batch: x={x.shape}, y={y.shape}")
            break
        print("  ✓ Burgers loader works!")
    except Exception as e:
        print(f"  ✗ Burgers failed: {e}")
    
    print("\nDone!")
